# -*- coding: utf-8 -*-
"""merged.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLXzCM16XZixeNC9oieA5lfoVMGkzXIe
"""

# juntar el csv
import pandas as pd

bdata = pd.read_csv("books_data.csv")
films = pd.read_csv("films.csv")

# combinar por columnas donde coincidan nombre del libro y fiction_work

merged_df = bdata.merge(films, left_on="Title", right_on="fiction_work")

#año
merged_df["film_year"] = merged_df["film_adaptation"].str.extract(r"\((\d{4})\)")

result = merged_df[["fiction_work", "film_year"]]
result.to_csv("nombres.txt", index=False, header=False, sep=";")

films.head()

bdata.shape

films.shape

merged_df.shape

frankenstein_df = merged_df[merged_df["fiction_work"] == "Frankenstein"]
frankenstein_df.head()